"""Machine-readable catalog of every method axis in the study.

Status values:
    implemented - resolves in the corresponding registry and is covered by tests
    planned     - registered as future work; raises KeyError if requested

Every citation key refers to references.bib.
"""

from . import fitters, knots, representations, samplers, timeparam

REPRESENTATION_CATALOG = {
    "linear": ("implemented", "deboor1978"),
    "hermite": ("implemented", "park2024splinegs"),
    "catmull_rom": ("implemented", "catmull1974"),
    "bspline2": ("implemented", "deboor1978"),
    "bspline3": ("implemented", "deboor1978"),
    "bspline5": ("implemented", "deboor1978"),
    "bspline7": ("implemented", "deboor1978"),
    "pspline": ("implemented", "eilers1996"),
    "chebyshev": ("implemented", "trefethen2013"),
    "fourier": ("implemented", ""),
    "nurbs": ("implemented", "piegl1995"),
    "akima": ("implemented", "akima1970"),
    "pchip": ("implemented", "fritsch1980"),
    "gp_rbf": ("implemented", "rasmussen2006"),
    "gp_matern52": ("implemented", "rasmussen2006"),
    "dmp": ("implemented", "ijspeert2013"),
    "mlp": ("implemented", "sitzmann2020"),
    "bspline_mlp": ("implemented", ""),
    "quadratic": ("planned", "deboor1978"),
    "quintic": ("planned", "deboor1978"),
    "septic": ("planned", "deboor1978"),
    "quintic_hermite": ("planned", ""),
    "bezier": ("planned", ""),
    "rational_bezier": ("planned", "piegl1995"),
    "composite_bezier": ("planned", ""),
    "uniform_bspline": ("planned", "deboor1978"),
    "nonuniform_bspline": ("planned", "deboor1978"),
    "clamped_bspline": ("planned", "deboor1978"),
    "periodic_bspline": ("planned", "deboor1978"),
    "quasi_uniform_bspline": ("planned", "deboor1978"),
    "tspline": ("planned", "sederberg2003"),
    "lr_bspline": ("planned", "dokken2013"),
    "hierarchical_bspline": ("planned", "forsey1988"),
    "mspline": ("planned", "ramsay1988"),
    "ispline": ("planned", "ramsay1988"),
    "penalized_spline": ("planned", "eilers1996"),
    "smoothing_spline": ("planned", "wahba1990"),
    "regression_spline": ("planned", "wahba1990"),
    "kochanek_bartels": ("planned", "kochanek1984"),
    "tcb": ("planned", "kochanek1984"),
    "akima_periodic": ("planned", "akima1970"),
    "fritsch_carlson_monotone": ("planned", "fritsch1980"),
    "steffen": ("planned", "steffen1990"),
    "thin_plate": ("planned", "duchon1977"),
    "polyharmonic": ("planned", "duchon1977"),
    "rbf_kernel_ridge": ("planned", "rasmussen2006"),
    "wavelet": ("planned", ""),
    "legendre": ("planned", "trefethen2013"),
    "bernstein": ("planned", ""),
    "lagrange": ("planned", ""),
    "newton_divided": ("planned", ""),
    "exponential_spline": ("planned", ""),
    "trigonometric_spline": ("planned", ""),
    "l_spline": ("planned", ""),
    "box_spline": ("planned", ""),
    "chaikin": ("planned", "chaikin1974"),
    "catmull_clark": ("planned", "catmull1978"),
    "loop_subdivision": ("planned", "loop1987"),
    "doo_sabin": ("planned", "doo1978"),
    "slerp": ("planned", "shoemake1985"),
    "squad": ("planned", "shoemake1987"),
    "so3_bezier": ("planned", "park1997"),
    "so3_bspline": ("planned", "kim1995"),
    "se3_screw": ("planned", ""),
    "dual_quaternion_spline": ("planned", "kavan2007"),
    "riemannian_spline": ("planned", "park1997"),
    "promp": ("planned", "paraschos2013"),
    "prodmp": ("planned", ""),
    "bayesian_interaction_primitive": ("planned", "benamor2014"),
    "gmm_gmr": ("planned", "calinon2007"),
    "hmm": ("planned", ""),
    "neural_ode": ("planned", "chen2018"),
    "siren": ("planned", "sitzmann2020"),
    "implicit_neural": ("planned", "sitzmann2020"),
    "neural_spline_flow": ("planned", "durkan2019"),
    "diffusion_policy": ("planned", "chi2023"),
    "transformer_policy": ("planned", ""),
    "minimum_jerk_poly": ("planned", "hogan1984"),
    "minimum_snap_poly": ("planned", "mellinger2011"),
    "bang_bang": ("planned", ""),
    "trapezoidal": ("planned", ""),
    "s_curve": ("planned", ""),
    "asymmetric_s_curve": ("planned", ""),
    "topp": ("planned", "pham2014"),
    "spline_gp_residual": ("planned", "rasmussen2006"),
    "spline_neural_residual": ("planned", "sitzmann2020"),
    "spline_mpc": ("planned", ""),
}

KNOT_CATALOG = {
    "uniform": ("implemented", "deboor1978"),
    "quantile": ("implemented", ""),
    "chord": ("implemented", ""),
    "centripetal": ("implemented", ""),
    "curvature": ("implemented", ""),
    "feature_peaks": ("implemented", ""),
    "rdp": ("implemented", "ramer1972"),
    "split_merge": ("implemented", ""),
    "greedy": ("implemented", "tropp2007"),
    "kmeans": ("implemented", ""),
    "farthest_point": ("implemented", "elden1997"),
    "bayesopt": ("implemented", "snoek2012"),
    "active_residual": ("implemented", "cohn1996"),
    "foley": ("planned", ""),
    "universal": ("planned", ""),
    "corner_detection": ("planned", ""),
    "velocity_peaks": ("planned", ""),
    "acceleration_peaks": ("planned", ""),
    "jerk_peaks": ("planned", ""),
    "zero_crossings": ("planned", ""),
    "acceleration_reversals": ("planned", ""),
    "impact_events": ("planned", ""),
    "via_points": ("planned", ""),
    "manual_keyframes": ("planned", ""),
    "mocap_markers": ("planned", ""),
    "semantic_boundaries": ("planned", ""),
    "douglas_peucker": ("planned", "ramer1972"),
    "orthogonal_matching_pursuit": ("planned", "tropp2007"),
    "lars": ("planned", "efron2004"),
    "genetic": ("planned", ""),
    "pso": ("planned", "kennedy1995"),
    "simulated_annealing": ("planned", ""),
    "cmaes_knots": ("planned", "hansen2001"),
    "gmm_placement": ("planned", ""),
    "dynamic_programming": ("planned", ""),
    "dtw": ("planned", ""),
    "pca": ("planned", ""),
    "autoencoder": ("planned", ""),
    "incremental_insertion": ("planned", ""),
    "multiresolution": ("planned", ""),
    "cross_validation": ("planned", "wahba1990"),
    "aic_bic_mdl": ("planned", ""),
    "expected_error_reduction": ("planned", "cohn1996"),
    "d_optimal": ("planned", "pukelsheim2006"),
    "sobol_knots": ("planned", "sobol1967"),
    "poisson_disk": ("planned", ""),
    "adversarial": ("planned", ""),
}

FITTER_CATALOG = {
    "least_squares": ("implemented", ""),
    "weighted": ("implemented", ""),
    "ridge": ("implemented", ""),
    "huber": ("implemented", "huber1964"),
    "ransac": ("implemented", "fischler1981"),
    "lasso": ("implemented", "tibshirani1996"),
    "elastic_net": ("implemented", "zou2005"),
    "tv": ("implemented", "rudin1992"),
    "adam": ("implemented", "kingma2015"),
    "lm": ("implemented", "levenberg1944"),
    "trf": ("implemented", "branch2000"),
    "dogbox": ("implemented", ""),
    "nelder_mead": ("implemented", "nelder1965"),
    "powell": ("implemented", "powell1964"),
    "differential_evolution": ("implemented", "storn1997"),
    "bayes_opt": ("implemented", "snoek2012"),
    "generalized_least_squares": ("planned", ""),
    "group_lasso": ("planned", ""),
    "sparse_bayesian_learning": ("planned", ""),
    "compressed_sensing": ("planned", "candes2008"),
    "tukey_bisquare": ("planned", ""),
    "cauchy_loss": ("planned", ""),
    "irls": ("implemented", "huber1964"),
    "trimmed_least_squares": ("planned", ""),
    "gauss_newton": ("planned", ""),
    "trust_region": ("planned", ""),
    "dogleg": ("planned", ""),
    "powell_hybrid": ("planned", ""),
    "sgd": ("planned", ""),
    "momentum": ("planned", ""),
    "nesterov": ("planned", ""),
    "rmsprop": ("planned", ""),
    "conjugate_gradient": ("planned", ""),
    "lbfgs": ("planned", ""),
    "bfgs": ("planned", ""),
    "dfp": ("planned", ""),
    "random_search": ("planned", ""),
    "grid_search": ("planned", ""),
    "genetic": ("planned", ""),
    "cmaes": ("planned", "hansen2001"),
    "particle_swarm": ("planned", "kennedy1995"),
    "ant_colony": ("planned", ""),
    "tpe": ("planned", ""),
    "hyperband": ("planned", ""),
    "quadratic_programming": ("planned", ""),
    "linear_programming": ("planned", ""),
    "socp": ("planned", ""),
    "sdp": ("planned", ""),
    "sqp": ("planned", ""),
    "interior_point": ("planned", ""),
    "augmented_lagrangian": ("planned", ""),
    "admm": ("planned", ""),
    "projected_gradient": ("planned", ""),
    "proximal_gradient": ("planned", ""),
    "frank_wolfe": ("planned", ""),
    "dynamic_programming": ("planned", ""),
    "branch_and_bound": ("planned", ""),
    "milp": ("planned", ""),
    "direct_shooting": ("planned", ""),
    "multiple_shooting": ("planned", ""),
    "direct_collocation": ("planned", ""),
    "ilqr": ("planned", "li2004"),
    "ddp": ("planned", "mayne1966"),
    "mpc": ("planned", ""),
    "chomp": ("planned", "zucker2013"),
    "stomp": ("planned", "kalakrishnan2011"),
    "trajopt": ("planned", "schulman2014"),
    "gpmp2": ("planned", "mukadam2018"),
    "max_entropy_irl": ("planned", "ziebart2008"),
    "behavior_cloning": ("planned", ""),
    "dagger": ("planned", "ross2011"),
    "ppo": ("planned", "schulman2017"),
    "sac": ("planned", "haarnoja2018"),
    "td3": ("planned", "fujimoto2018"),
    "ddpg": ("planned", "lillicrap2016"),
    "a3c": ("planned", "mnih2016"),
    "evolutionary_strategies": ("planned", ""),
    "maml": ("planned", "finn2017"),
    "reptile": ("planned", "nichol2018"),
    "pin": ("planned", "raissi2019"),
    "differentiable_spline": ("planned", ""),
}

SAMPLING_CATALOG = {
    "random": ("implemented", ""),
    "grid": ("implemented", ""),
    "stratified": ("implemented", "mckay1979"),
    "lhs": ("implemented", "mckay1979"),
    "sobol": ("implemented", "sobol1967"),
    "halton": ("implemented", ""),
    "farthest_point": ("implemented", "elden1997"),
    "jerk_importance": ("implemented", ""),
    "derivative_peaks": ("implemented", ""),
    "hybrid": ("implemented", ""),
    "active_gp": ("implemented", "cohn1996"),
    "active_residual": ("implemented", ""),
    "query_by_committee": ("implemented", "seung1992"),
    "poisson_disk": ("planned", ""),
    "expected_error_reduction": ("planned", "cohn1996"),
    "expected_model_change": ("planned", "mackay1992"),
    "bayesian_experimental_design": ("planned", "chaloner1995"),
    "d_optimal": ("planned", "pukelsheim2006"),
    "a_optimal": ("planned", "pukelsheim2006"),
    "e_optimal": ("planned", "pukelsheim2006"),
    "recursive_least_squares": ("planned", ""),
    "kalman": ("planned", "kalman1960"),
    "particle_filter": ("planned", "thrun2005"),
    "incremental_knot_insertion": ("planned", ""),
    "compressed_sensing": ("planned", "candes2008"),
    "adversarial": ("planned", ""),
    "transfer_meta_learning": ("planned", "finn2017"),
}

TIME_PARAM_CATALOG = {
    "linear": ("implemented", ""),
    "chord": ("implemented", ""),
    "centripetal": ("implemented", ""),
    "accel": ("implemented", ""),
    "jerk": ("implemented", ""),
    "foley": ("planned", ""),
    "universal": ("planned", ""),
    "quantile": ("planned", ""),
    "asymmetric_time_scaling": ("planned", ""),
    "learned_timing_law": ("planned", ""),
}

METRIC_CATALOG = {
    "pos_rmse": ("implemented", ""),
    "pos_mae": ("implemented", ""),
    "pos_max": ("implemented", ""),
    "vel_rmse": ("implemented", ""),
    "vel_nrmse": ("implemented", ""),
    "acc_rmse": ("implemented", ""),
    "acc_nrmse": ("implemented", ""),
    "jerk_rmse": ("implemented", ""),
    "jerk_nrmse": ("implemented", ""),
    "snap_rmse": ("implemented", ""),
    "snap_nrmse": ("implemented", ""),
    "peak_time_err": ("implemented", ""),
    "overshoot": ("implemented", ""),
    "settle_time_err": ("implemented", ""),
    "isj_ratio": ("implemented", ""),
    "cstr_v_mean": ("implemented", ""),
    "cstr_a_mean": ("implemented", ""),
    "cstr_j_mean": ("implemented", ""),
    "train_rmse": ("implemented", ""),
    "aulc": ("implemented", ""),
    "fit_time_s": ("implemented", ""),
    "n_params": ("implemented", ""),
    "n_params_total": ("implemented", ""),
    "robustness_noise": ("implemented", ""),
    "robustness_outliers": ("implemented", ""),
    "robustness_missing": ("implemented", ""),
    "extrapolation": ("planned", ""),
}

CATALOG = {
    "representations": REPRESENTATION_CATALOG,
    "knots": KNOT_CATALOG,
    "fitters": FITTER_CATALOG,
    "sampling": SAMPLING_CATALOG,
    "time_param": TIME_PARAM_CATALOG,
    "metrics": METRIC_CATALOG,
}


def methods(axis, status=None):
    entries = CATALOG[axis]
    return sorted(k for k, v in entries.items() if status is None or v[0] == status)


def implemented(axis):
    return methods(axis, "implemented")


def planned(axis):
    return methods(axis, "planned")


def citation(axis, name):
    return CATALOG[axis].get(name, (None, ""))[1]


def registry_methods(axis):
    if axis == "representations":
        return set(representations.list_representations())
    if axis == "knots":
        return set(knots.list_knot_placers())
    if axis == "sampling":
        return set(samplers.list_samplers())
    if axis == "time_param":
        return set(timeparam.list_time_params())
    if axis == "fitters":
        return set(fitters.LINEAR_FITTERS) | set(fitters.NONLINEAR_METHODS) | {"irls"}
    return set()
